Vagrant.configure("2") do |config|

  config.vm.define "host1" do |host1|
    host1.vm.box = "ubuntu/trusty64"
    host1.vm.hostname = "ubuntu1"
    host1.vm.network :private_network, ip: "192.168.2.1"
    host1.vm.provider "vmware_fusion" do |v|
      v.gui = true
    end
  end

  config.vm.define "host2" do |host2|
    host2.vm.box = "ubuntu/trusty64"
    host2.vm.hostname = "ubuntu2"
    host2.vm.network :private_network, ip: "192.168.2.2"
    host2.vm.provider "vmware_fusion" do |v|
      v.gui = true
    end
  end
end
